modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="batnetwork"
version="${file.jarVersion}"
displayName="BatNetwork"
credits="Made by Zeldown"
authors="Zeldown"
description='''
BatNetwork
'''
[[dependencies.batnetwork]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.batnetwork]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"